/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demomysqljavanetbeans;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sala306
 */
public class JFrameFormulario extends javax.swing.JFrame {

    DefaultTableModel ptabla = new DefaultTableModel();
    Connection cn;
    PreparedStatement pst;
    ResultSet resultadoConsulta;

    /**
     * Creates new form JFrameFormulario
     */
    public JFrameFormulario() {
        initComponents();
        String tit[] = {"Id", "Código", "Nombre", "Fecha"};
        ptabla.setColumnIdentifiers(tit);
        tablaVariable.setModel(ptabla);
        this.Identificador.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoFecha = new javax.swing.JTextField();
        Identificador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVariable = new javax.swing.JTable();
        BotonRefresca = new javax.swing.JButton();
        BotonInserta = new javax.swing.JButton();
        BotonModifica = new javax.swing.JButton();
        Belimina = new javax.swing.JButton();
        BotonBusca = new javax.swing.JButton();
        BLimpia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Taller base de datos MySQL con UsbWebservice");

        jLabel2.setText("Código");

        jLabel3.setText("Nombre");

        jLabel4.setText("Fecha AA-MM-DD");

        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });

        tablaVariable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVariable);

        BotonRefresca.setText("Refresca");
        BotonRefresca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRefrescaActionPerformed(evt);
            }
        });

        BotonInserta.setText("Inserta");
        BotonInserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInsertaActionPerformed(evt);
            }
        });

        BotonModifica.setText("Modifica");

        Belimina.setText("Elimina ");
        Belimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliminaActionPerformed(evt);
            }
        });

        BotonBusca.setText("Busca");
        BotonBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscaActionPerformed(evt);
            }
        });

        BLimpia.setText("Limpia");
        BLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLimpiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Identificador, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(campoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotonRefresca)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonInserta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonModifica)
                        .addGap(18, 18, 18)
                        .addComponent(Belimina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonBusca)
                        .addGap(18, 18, 18)
                        .addComponent(BLimpia)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Identificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonRefresca)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonInserta)
                    .addComponent(BotonModifica)
                    .addComponent(Belimina)
                    .addComponent(BotonBusca)
                    .addComponent(BLimpia))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoActionPerformed

    private void BotonRefrescaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRefrescaActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

        try {
            cn = Connecta.abrebase();
            Statement s = cn.createStatement();
//consuta a mostrar
            String query = "select * from estudiante";
            resultadoConsulta = s.executeQuery(query);
            cargarResultados(resultadoConsulta);
            cn.close();
        } catch (Exception e) {
             e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);//
        }
    }//GEN-LAST:event_BotonRefrescaActionPerformed

    private void cargarResultados(ResultSet resultadoConsulta) throws SQLException {
        System.out.println(resultadoConsulta);
        ResultSetMetaData rsmd = resultadoConsulta.getMetaData();
        DefaultTableModel tablaResultados = new DefaultTableModel();
        tablaVariable.setModel(tablaResultados);
//obtenemos numero de columnas
        int CanColumns = rsmd.getColumnCount();
//comprobamos
//System.out.println(CanColumns);
        for (int i = 1; i <= CanColumns; i++) {
//cargamos columnas en modelo
//modelo.addColumn(rsmd.getColumnLabel(i));
            tablaResultados.addColumn(rsmd.getColumnLabel(i));
        }
        while (resultadoConsulta.next()) { //Iterar a través de los resultados
//creamos array
            Object[] fila = new Object[CanColumns];
//cargamos datos a modelo
            for (int i = 0; i < CanColumns; i++) {
                fila[i] = resultadoConsulta.getObject(i + 1);
//System.out.print ln(fila[i]);
            }
//adiciona fila
            tablaResultados.addRow(fila);
        }
    }

    private void BotonInsertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInsertaActionPerformed
       SimpleDateFormat formato = new SimpleDateFormat("yy-MM-dd");
// TODO add your handling code here:
        try {
            cn = Connecta.abrebase();
            pst = cn.prepareStatement("INSERT INTO estudiante (codigo, nombre,fecha) VALUES (?,?,?)");
            pst.setString(1, campoCodigo.getText());
            pst.setString(2, campoNombre.getText());
            pst.setDate(3,new java.sql.Date(formato.parse(campoFecha.getText()).getTime()));
            int res = pst.executeUpdate();
            if (res > 0) {
                mensaje("Estudiante ingresado");
                blancos();
            } else {
                mensaje("Error");
                blancos();
            }
            cn.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
        }

    }//GEN-LAST:event_BotonInsertaActionPerformed

    private void BotonBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscaActionPerformed

        try {
            cn = Connecta.abrebase();
            String sql = "SELECT * FROM estudiante WHERE codigo = ?";
            PreparedStatement statement = cn.prepareStatement(sql);
            statement.setInt(1, Integer.parseInt(campoCodigo.getText()));
            ResultSet resultado = statement.executeQuery();
            cargarResultados(resultado);
            cn.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);//
        }
    }//GEN-LAST:event_BotonBuscaActionPerformed

    private void BeliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliminaActionPerformed
        try {
            cn = Connecta.abrebase();
            int filaSeleccionada = tablaVariable.getSelectedRow();
            if (filaSeleccionada == -1) {
                JOptionPane.showMessageDialog(null, "Error seleccione una fila de la tabla");
            } else {
                String codigo = String.valueOf(tablaVariable.getValueAt(filaSeleccionada, 1));
                String sql = "DELETE FROM estudiante Where codigo = ? ";
                PreparedStatement statement = cn.prepareStatement(sql);
                statement.setString(1, codigo);
                int cantidadFilasModificadas = statement.executeUpdate();
                if (cantidadFilasModificadas == 0) {
                    JOptionPane.showMessageDialog(null, "No se eliminó ningun registro");//
                }
            }
            cn.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);//
        }
        BotonRefrescaActionPerformed(evt);
    }//GEN-LAST:event_BeliminaActionPerformed

    private void BLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLimpiaActionPerformed
       
       DefaultTableModel temp;
       try{
           temp=(DefaultTableModel) tablaVariable.getModel();
           int a = temp.getRowCount();
           for (int i=0;i<a;i++)
               temp.removeRow(0);
           
       } catch (Exception e){
           
           System.out.println(e);
       }
       
    }//GEN-LAST:event_BLimpiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BLimpia;
    private javax.swing.JButton Belimina;
    private javax.swing.JButton BotonBusca;
    private javax.swing.JButton BotonInserta;
    private javax.swing.JButton BotonModifica;
    private javax.swing.JButton BotonRefresca;
    private javax.swing.JTextField Identificador;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoFecha;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVariable;
    // End of variables declaration//GEN-END:variables

    public void blancos() {
        Identificador.setText(null);
        campoCodigo.setText(null);
        campoNombre.setText(null);
        campoFecha.setText(null);
        campoCodigo.setEditable(true);
        campoCodigo.requestFocus();
    }

    public void mensaje(String cad) {
        JOptionPane.showMessageDialog(null, cad);
    }

}
